// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.0
// source: cat.proto

package pets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight int32  `protobuf:"varint,1,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Color  string `protobuf:"bytes,2,opt,name=Color,proto3" json:"Color,omitempty"`
	Age    int32  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *Cat) Reset() {
	*x = Cat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{0}
}

func (x *Cat) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Cat) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Cat) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Cat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_cat_proto protoreflect.FileDescriptor

var file_cat_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x65, 0x74,
	0x73, 0x22, 0x59, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x42, 0x18, 0x5a, 0x16,
	0x70, 0x65, 0x74, 0x73, 0x76, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cat_proto_rawDescOnce sync.Once
	file_cat_proto_rawDescData = file_cat_proto_rawDesc
)

func file_cat_proto_rawDescGZIP() []byte {
	file_cat_proto_rawDescOnce.Do(func() {
		file_cat_proto_rawDescData = protoimpl.X.CompressGZIP(file_cat_proto_rawDescData)
	})
	return file_cat_proto_rawDescData
}

var file_cat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cat_proto_goTypes = []interface{}{
	(*Cat)(nil), // 0: pets.Cat
}
var file_cat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cat_proto_init() }
func file_cat_proto_init() {
	if File_cat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cat_proto_goTypes,
		DependencyIndexes: file_cat_proto_depIdxs,
		MessageInfos:      file_cat_proto_msgTypes,
	}.Build()
	File_cat_proto = out.File
	file_cat_proto_rawDesc = nil
	file_cat_proto_goTypes = nil
	file_cat_proto_depIdxs = nil
}
